#import './expenseType.gql'

fragment ExpenseFragment on Expense {
  id
  unit {
    id
    code
    name
  }
  comments
  vendor {
    id
    code
    name
  }
  period {
    id
    periodEnd
    pivot {
      isClosed
    }
  }
  expenseDate
  glAccount {
    id
    name
  }
  expenseType {
    ...ExpenseTypeFragment
  }
  amount
}
