#import './glAccount.gql'
#import './inventoryCategory.gql'

fragment PurchaseChargeFragment on PurchaseCharge {
  id
  amount
  glAccount {
    ...GlAccountFragment
  }
  purchase {
    id
    number
  }
  inventoryCategory {
    ...InventoryCategoryFragment
  }
}
