#import './county.gql'
#import './city.gql'

fragment StateFragment on State {
  id
  code
  counties {
    ...CountyFragment
  }
  cities {
    ...CityFragment
  }
  salesTaxCafeteria
  salesTaxVending
  salesTaxRestaurant
  salesTaxStore
  grossReceiptsTax
  createdAt
  updatedAt
}
