#import '../fragments/role.gql'

query RoleList($page: Int!) {
  roleList(page: $page) {
    paginatorInfo {
      count
      perPage
      total
      
      firstItem
      lastItem
      
      currentPage
      lastPage
      hasMorePages
    }
    data {
        ...RoleFragment
    }
  }
}
