#import '../fragments/glAccount.gql'

query UnitsByGLAccount {
  unitsByGLAccount {
    id
    code
    name
    glAccounts {
        ...GlAccountFragment
        parent {
            id
            itemId
            name
            glTypeCode {
                id
                description
            }
        }
        child {
            id
            itemId
            name
        }
    }
  }
}
