#import '../fragments/glAccount.gql'

query UserGlAccounts {
  UserGlAccounts {
    ...GlAccountFragment
    parent {
      id
      itemId
      name
    }
    child {
      id
      itemId
      name
    }
  }
}
