<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['name' => 'Alexandria', 'state' => 'VA', 'tax' => '0'],
            ['name' => 'Allentown', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Amenia', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Annapolis', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Ashburnham', 'state' => 'MA', 'tax' => '0'],
            ['name' => 'Baltimore', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Berwyn', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Bethlehem', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Blue Bell', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Bridgewater', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Bristol', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Brookline', 'state' => 'MA', 'tax' => '0'],
            ['name' => 'Camden', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Centennial', 'state' => 'CO', 'tax' => '0.0275'],
            ['name' => 'Chadds Ford', 'state' => 'pa', 'tax' => '0'],
            ['name' => 'Charlottesville', 'state' => 'VA', 'tax' => '0.033'],
            ['name' => 'Chester', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'College Park', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Colora', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Colorado Springs', 'state' => 'CO', 'tax' => '0.0363'],
            ['name' => 'Columbia', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Conshohocken', 'state' => 'pA', 'tax' => '0'],
            ['name' => 'Coopersburg', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Denver', 'state' => 'CO', 'tax' => '0'],
            ['name' => 'Denver', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Dobbs Ferry', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Dover', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'E Greenwich', 'state' => 'RI', 'tax' => '0'],
            ['name' => 'East Grnville', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Easton', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Elkton', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Englewood', 'state' => 'CO', 'tax' => '0.01'],
            ['name' => 'Exton', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Far Hills', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Farmington', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Florham Park', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Fort Washington', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Frazer', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Frederice', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'Germantown', 'state' => 'mD', 'tax' => '0'],
            ['name' => 'Gladstone', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Greenwich', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Hammonton', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Harbeson', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'Harrisburg', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Hatboro', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Hockessin', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'Horsham', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Inverness', 'state' => 'CO', 'tax' => '0.0025'],
            ['name' => 'Iselin', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'King of Prussia', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Lansdale', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Lester', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Lexington', 'state' => 'MA', 'tax' => '0'],
            ['name' => 'Liberty Corner', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Littleton', 'state' => 'CO', 'tax' => '0.0325'],
            ['name' => 'Lower Gwynedd', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Lusby', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Lyndon Center', 'state' => 'VT', 'tax' => '0'],
            ['name' => 'Malvern', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Marietta', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Marlborough', 'state' => 'MA', 'tax' => '0'],
            ['name' => 'Meadowbrook', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Media', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Middletown', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Milford', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'Monmouth Junction', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Morristown', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Morrisville', 'state' => 'NC', 'tax' => '0'],
            ['name' => 'Mount Olive', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Natick', 'state' => 'MA', 'tax' => '0'],
            ['name' => 'New Castle', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'New Lebanon', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'New York', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Newark', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'Norristown', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'North Wales', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Oradell', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Owings Mills', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Paoli', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Parsippany', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Pennsauken', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Pennsville', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Philadelphia', 'state' => 'PA', 'tax' => '0.02'],
            ['name' => 'Piscataway', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Plymouth Meeting', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Pomfret Center', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Poughkeepsie', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Prides Crossing', 'state' => 'MA', 'tax' => '0'],
            ['name' => 'Princeton', 'state' => 'nJ', 'tax' => '0'],
            ['name' => 'Providence', 'state' => 'RI', 'tax' => '0'],
            ['name' => 'Radnor', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Raleigh', 'state' => 'NC', 'tax' => '0'],
            ['name' => 'Reading', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Research Triangle', 'state' => 'NC', 'tax' => '0'],
            ['name' => 'Reston', 'state' => 'VA', 'tax' => '0'],
            ['name' => 'Rockville', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Roslyn', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Saltzburg', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Severn', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Silver Springs', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Smithtown', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Southport', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Springfield', 'state' => 'VA', 'tax' => '0'],
            ['name' => 'Stamford', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Stevenson', 'state' => 'MD', 'tax' => '0'],
            ['name' => 'Syracuse', 'state' => 'NY', 'tax' => '0'],
            ['name' => 'Telford', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Totowa', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Trenton', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Trevose', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Vienna', 'state' => 'VA', 'tax' => '0.01'],
            ['name' => 'Villanova', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'Warren', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Washington', 'state' => 'DC', 'tax' => '0'],
            ['name' => 'West  Trenton', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'West Chester', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'West Depford', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'West Hartford', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Wilmington', 'state' => 'DE', 'tax' => '0'],
            ['name' => 'Woodbridge', 'state' => 'NJ', 'tax' => '0'],
            ['name' => 'Woodstock', 'state' => 'CT', 'tax' => '0'],
            ['name' => 'Woodstock', 'state' => 'VA', 'tax' => '0'],
            ['name' => 'Yardley', 'state' => 'PA', 'tax' => '0'],
            ['name' => 'York', 'state' => 'PA', 'tax' => '0'],
        ];

        foreach ($cities as $city)
            City::create([
                'name'     => $city['name'],
                'state_id' => \App\Models\State::where('code', $city['state'])->first()->id,
                'tax'      => $city['tax'],
            ]);
    }
}
