<?php

namespace Database\Seeders;

use App\Models\GlAccount;
use Illuminate\Database\Seeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class GlAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $glAccounts = [
            ['old_id' => '1010', 'gl_type_code' => 'corp', 'name' => 'Cash Savings'],
            ['old_id' => '1020', 'gl_type_code' => 'corp', 'name' => 'Cash Executive Payroll'],
            ['old_id' => '1025', 'gl_type_code' => 'corp', 'name' => 'Cash Main Payroll'],
            ['old_id' => '1030', 'gl_type_code' => 'corp', 'name' => 'Cash Main Account'],
            ['old_id' => '1035', 'gl_type_code' => 'corp', 'name' => 'Cash Main Account'],
            ['old_id' => '1040', 'gl_type_code' => 'sales', 'name' => 'Cash Depository Bank'],
            ['old_id' => '1050', 'gl_type_code' => 'expense', 'name' => 'Petty Cash'],
            ['old_id' => '1070', 'gl_type_code' => 'corp', 'name' => 'Investments'],
            ['old_id' => '1100', 'gl_type_code' => 'corp', 'name' => 'Accounts Receivable'],
            ['old_id' => '1110', 'gl_type_code' => 'corp', 'name' => 'Reserve For Bad Debts'],
            ['old_id' => '1120', 'gl_type_code' => 'corp', 'name' => 'Dividend Receivable'],
            ['old_id' => '1130', 'gl_type_code' => 'corp', 'name' => 'Cobra Receivable'],
            ['old_id' => '1140', 'gl_type_code' => 'corp', 'name' => 'Deposits And Exchanges'],
            ['old_id' => '1144', 'gl_type_code' => 'corp', 'name' => 'Misc. Receivables'],
            ['old_id' => '1150', 'gl_type_code' => 'sales', 'name' => 'Credit Cards Rec'],
            ['old_id' => '1180', 'gl_type_code' => 'corp', 'name' => 'Rec From Vend Mach - Unisys Va'],
            ['old_id' => '1200', 'gl_type_code' => 'foo', 'name' => 'Inventory'],
            ['old_id' => '1300', 'gl_type_code' => 'corp', 'name' => 'Prepaid Expenses/Insurance'],
            ['old_id' => '1310', 'gl_type_code' => 'corp', 'name' => 'Prepaid Wkmn\'s Comp Premium'],
            ['old_id' => '1330', 'gl_type_code' => 'corp', 'name' => 'Prepaid State Taxes'],
            ['old_id' => '1370', 'gl_type_code' => 'corp', 'name' => 'Prepaid Other Expenses'],
            ['old_id' => '1505', 'gl_type_code' => 'corp', 'name' => 'Auto'],
            ['old_id' => '1507', 'gl_type_code' => 'corp', 'name' => 'Office Machinery & Equipment'],
            ['old_id' => '1509', 'gl_type_code' => 'corp', 'name' => 'Computer Equipment'],
            ['old_id' => '1510', 'gl_type_code' => 'corp', 'name' => 'Computer Software'],
            ['old_id' => '1511', 'gl_type_code' => 'corp', 'name' => 'Brock Cafeteria Equipment'],
            ['old_id' => '1516', 'gl_type_code' => 'corp', 'name' => 'Res For Cafeteria Vehicles'],
            ['old_id' => '1531', 'gl_type_code' => 'corp', 'name' => 'NCI Restaurant Equipment'],
            ['old_id' => '1580', 'gl_type_code' => 'corp', 'name' => 'Vending Factory Mach/Equip'],
            ['old_id' => '1584', 'gl_type_code' => 'corp', 'name' => 'Vending Machines'],
            ['old_id' => '1585', 'gl_type_code' => 'corp', 'name' => 'Vending Vehicles'],
            ['old_id' => '2000', 'gl_type_code' => 'corp', 'name' => 'Accounts Payable'],
            ['old_id' => '2001', 'gl_type_code' => 'corp', 'name' => 'A/P Accruals And Reversals'],
            ['old_id' => '2010', 'gl_type_code' => 'corp', 'name' => 'Accounts Payable'],
            ['old_id' => '2015', 'gl_type_code' => 'corp', 'name' => 'Accts Payable On Contracts 106'],
            ['old_id' => '2020', 'gl_type_code' => 'corp', 'name' => 'Payroll Payable'],
            ['old_id' => '2025', 'gl_type_code' => 'corp', 'name' => 'Accrued Payroll Incentives'],
            ['old_id' => '2100', 'gl_type_code' => 'corp', 'name' => 'Federal Income Tax Withheld'],
            ['old_id' => '2110', 'gl_type_code' => 'corp', 'name' => 'Fica Taxes Withheld'],
            ['old_id' => '2120', 'gl_type_code' => 'corp', 'name' => 'Pa Income Tax Withheld'],
            ['old_id' => '2130', 'gl_type_code' => 'corp', 'name' => 'NJ Income Tax Withheld'],
            ['old_id' => '2135', 'gl_type_code' => 'corp', 'name' => 'NY Income Tax Withheld'],
            ['old_id' => '2140', 'gl_type_code' => 'corp', 'name' => 'DE Income Tax Withheld'],
            ['old_id' => '2145', 'gl_type_code' => 'corp', 'name' => 'VA Income Taxes Withheld'],
            ['old_id' => '2150', 'gl_type_code' => 'corp', 'name' => 'MD Income Taxes Withheld'],
            ['old_id' => '2155', 'gl_type_code' => 'corp', 'name' => 'Washington DC W/H Tax'],
            ['old_id' => '2160', 'gl_type_code' => 'corp', 'name' => 'Phila Wage Tax Withheld'],
            ['old_id' => '2165', 'gl_type_code' => 'corp', 'name' => 'Whitpain Township Wages W/H'],
            ['old_id' => '2170', 'gl_type_code' => 'corp', 'name' => 'Chester Wage Tax Withheld'],
            ['old_id' => '2175', 'gl_type_code' => 'corp', 'name' => 'Wilmington Wage Taxes Withheld'],
            ['old_id' => '2180', 'gl_type_code' => 'corp', 'name' => 'Local Taxes Withheld'],
            ['old_id' => '2181', 'gl_type_code' => 'corp', 'name' => 'Central Tax-W.Brandywine W/H'],
            ['old_id' => '2182', 'gl_type_code' => 'corp', 'name' => 'Del. Valley Tax-W.Brandy W/H'],
            ['old_id' => '2185', 'gl_type_code' => 'corp', 'name' => 'East Fallowfield Twn 1%'],
            ['old_id' => '2190', 'gl_type_code' => 'corp', 'name' => 'Norristown/Norriton Local Tax'],
            ['old_id' => '2195', 'gl_type_code' => 'corp', 'name' => 'Occupational Privilege Tax'],
            ['old_id' => '2199', 'gl_type_code' => 'corp', 'name' => 'Berkheimer Taxes Withheld'],
            ['old_id' => '2240', 'gl_type_code' => 'corp', 'name' => '401k Payable'],
            ['old_id' => '2260', 'gl_type_code' => 'corp', 'name' => 'Vending Union Dues Withheld'],
            ['old_id' => '2265', 'gl_type_code' => 'corp', 'name' => 'Ford Union Dues Withheld'],
            ['old_id' => '2270', 'gl_type_code' => 'corp', 'name' => 'Wage Attachments Withheld'],
            ['old_id' => '2275', 'gl_type_code' => 'corp', 'name' => 'Payback On 401k Loans'],
            ['old_id' => '2280', 'gl_type_code' => 'corp', 'name' => 'Vending Bonds Holdings'],
            ['old_id' => '2300', 'gl_type_code' => 'corp', 'name' => 'Unemployment Taxes Payable'],
            ['old_id' => '2310', 'gl_type_code' => 'corp', 'name' => 'DE Unemployment Taxes Payable'],
            ['old_id' => '2320', 'gl_type_code' => 'corp', 'name' => 'NJ Unemployment Taxes Payable'],
            ['old_id' => '2330', 'gl_type_code' => 'corp', 'name' => 'MD Unemployment Taxes Payable'],
            ['old_id' => '2340', 'gl_type_code' => 'corp', 'name' => 'VA Unemployment Taxes Payable'],
            ['old_id' => '2350', 'gl_type_code' => 'corp', 'name' => 'FED Unemployment Taxes Payable'],
            ['old_id' => '2360', 'gl_type_code' => 'corp', 'name' => 'FICA Payable - Employers'],
            ['old_id' => '2365', 'gl_type_code' => 'corp', 'name' => 'Workmans Comp Payable'],
            ['old_id' => '2410', 'gl_type_code' => 'sales', 'name' => 'PA Sales Tax Payable'],
            ['old_id' => '2420', 'gl_type_code' => 'sales', 'name' => 'NJ Sales Tax Payable'],
            ['old_id' => '2430', 'gl_type_code' => 'corp', 'name' => 'DE Gross Receipts Tax Payable'],
            ['old_id' => '2440', 'gl_type_code' => 'sales', 'name' => 'MD Sales Tax Payable'],
            ['old_id' => '2445', 'gl_type_code' => 'sales', 'name' => 'NC Sales Tax Payable'],
            ['old_id' => '2450', 'gl_type_code' => 'sales', 'name' => 'VA Sales Taxes Payable'],
            ['old_id' => '2460', 'gl_type_code' => 'sales', 'name' => 'DC Sales Tax Payable'],
            ['old_id' => '2480', 'gl_type_code' => 'corp', 'name' => 'Phila Gross Receipts Tax Pay'],
            ['old_id' => '2500', 'gl_type_code' => 'corp', 'name' => 'Vacation Payable'],
            ['old_id' => '2700', 'gl_type_code' => 'corp', 'name' => 'Interest Payable On Debentures'],
            ['old_id' => '2710', 'gl_type_code' => 'corp', 'name' => 'Interest Payable Notes'],
            ['old_id' => '2800', 'gl_type_code' => 'corp', 'name' => 'Notes Payable'],
            ['old_id' => '2820', 'gl_type_code' => 'corp', 'name' => 'Debenture Bonds Payable'],
            ['old_id' => '2830', 'gl_type_code' => 'corp', 'name' => 'Notes Due Stockholders CNB'],
            ['old_id' => '2840', 'gl_type_code' => 'corp', 'name' => 'Notes Due Individuals CJB'],
            ['old_id' => '2850', 'gl_type_code' => 'corp', 'name' => 'Notes Due Stockholders LBJr'],
            ['old_id' => '3000', 'gl_type_code' => 'corp', 'name' => 'Common Stock Class A'],
            ['old_id' => '3300', 'gl_type_code' => 'corp', 'name' => 'Additional Paid In Capital'],
            ['old_id' => '3400', 'gl_type_code' => 'corp', 'name' => 'Contra Investments Bk To Mkt'],
            ['old_id' => '3500', 'gl_type_code' => 'corp', 'name' => 'S Corp Retained Earnings'],
            ['old_id' => '3510', 'gl_type_code' => 'corp', 'name' => 'C Corp Retained Earnings'],
            ['old_id' => '3520', 'gl_type_code' => 'corp', 'name' => 'Distributions/Withdrawals'],
            ['old_id' => '4200', 'gl_type_code' => 'sales', 'name' => 'Sales - Cafeteria Manual'],
            ['old_id' => '4210', 'gl_type_code' => 'sales', 'name' => 'Sales - Cafeteria Catering'],
            ['old_id' => '4215', 'gl_type_code' => 'sales', 'name' => 'Sales - Exempt Catering'],
            ['old_id' => '4220', 'gl_type_code' => 'sales', 'name' => 'Sales - Cafeteria OCS'],
            ['old_id' => '4230', 'gl_type_code' => 'sales', 'name' => 'Sales - Resident Vending'],
            ['old_id' => '4240', 'gl_type_code' => 'sales', 'name' => 'Sales - Restaurant Food'],
            ['old_id' => '4250', 'gl_type_code' => 'sales', 'name' => 'Employee Store Sales'],
            ['old_id' => '4280', 'gl_type_code' => 'corp', 'name' => 'Sales - Vending (Machine)'],
            ['old_id' => '4290', 'gl_type_code' => 'corp', 'name' => 'Sales - Vending OCS'],
            ['old_id' => '4400', 'gl_type_code' => 'sales', 'name' => 'Miscellaneous Inc From Outside'],
            ['old_id' => '4500', 'gl_type_code' => 'corp', 'name' => 'Service Fee Income'],
            ['old_id' => '4610', 'gl_type_code' => 'corp', 'name' => 'Misc Income Cafeterias'],
            ['old_id' => '4650', 'gl_type_code' => 'corp', 'name' => 'Misc Income Restaurant'],
            ['old_id' => '4680', 'gl_type_code' => 'corp', 'name' => 'Misc Income Vending'],
            ['old_id' => '4700', 'gl_type_code' => 'corp', 'name' => 'Transportation Income Catering'],
            ['old_id' => '4800', 'gl_type_code' => 'corp', 'name' => 'Cafeteria Income From Vending'],
            ['old_id' => '4930', 'gl_type_code' => 'corp', 'name' => 'Gain/Loss On Stock Investments'],
            ['old_id' => '4940', 'gl_type_code' => 'corp', 'name' => 'Interest Income - Other'],
            ['old_id' => '4950', 'gl_type_code' => 'corp', 'name' => 'P/L On Sale Of Assets'],
            ['old_id' => '4990', 'gl_type_code' => 'corp', 'name' => 'Cash Discounts'],
            ['old_id' => '5000', 'gl_type_code' => 'expense', 'name' => 'Food Costs - Cafeteria'],
            ['old_id' => '5030', 'gl_type_code' => 'expense', 'name' => 'Food Costs Resident Vending'],
            ['old_id' => '5050', 'gl_type_code' => 'expense', 'name' => 'Employee Store Product Costs'],
            ['old_id' => '5080', 'gl_type_code' => 'expense', 'name' => 'Food Costs Vending'],
            ['old_id' => '5090', 'gl_type_code' => 'expense', 'name' => 'Prod Costs - Vending OCS'],
            ['old_id' => '5100', 'gl_type_code' => 'expense', 'name' => 'Paper Costs - Cafeterias'],
            ['old_id' => '5130', 'gl_type_code' => 'expense', 'name' => 'Paper Costs - Vend Hot Cups/Ld'],
            ['old_id' => '5180', 'gl_type_code' => 'expense', 'name' => 'Paper Costs Vending'],
            ['old_id' => '5200', 'gl_type_code' => 'payroll', 'name' => 'Labor - Direct'],
            ['old_id' => '5210', 'gl_type_code' => 'corp', 'name' => 'Labor - Supervision'],
            ['old_id' => '5280', 'gl_type_code' => 'corp', 'name' => 'Labor - Vacation Accrual'],
            ['old_id' => '5299', 'gl_type_code' => 'corp', 'name' => 'Payroll Taxes'],
            ['old_id' => '5300', 'gl_type_code' => 'expense', 'name' => 'Sundry'],
            ['old_id' => '5400', 'gl_type_code' => 'expense', 'name' => 'Vending Commission Expenses'],
            ['old_id' => '5700', 'gl_type_code' => 'corp', 'name' => 'Unrecovered Contract Costs'],
            ['old_id' => '5800', 'gl_type_code' => 'corp', 'name' => 'Administration Allocation'],
            ['old_id' => '5900', 'gl_type_code' => 'corp', 'name' => 'Management Fee Allocation'],
            ['old_id' => '6100', 'gl_type_code' => 'corp', 'name' => 'Executive Salaries'],
            ['old_id' => '6200', 'gl_type_code' => 'corp', 'name' => 'Office Rents'],
            ['old_id' => '6300', 'gl_type_code' => 'corp', 'name' => 'Office Forms'],
            ['old_id' => '6400', 'gl_type_code' => 'corp', 'name' => 'Operations Expenses'],
            ['old_id' => '6500', 'gl_type_code' => 'corp', 'name' => 'Sales Expenses'],
            ['old_id' => '6600', 'gl_type_code' => 'corp', 'name' => 'Exec Auto Repairs'],
            ['old_id' => '6700', 'gl_type_code' => 'corp', 'name' => 'Corp. Public Relations'],
            ['old_id' => '7100', 'gl_type_code' => 'corp', 'name' => 'FICA Expense'],
            ['old_id' => '7500', 'gl_type_code' => 'corp', 'name' => 'Interest Expense'],
            ['old_id' => '7600', 'gl_type_code' => 'corp', 'name' => 'Extraordinary Expenses'],
            ['old_id' => '7700', 'gl_type_code' => 'corp', 'name' => 'Net Corp Income Taxes'],
            ['old_id' => '9300', 'gl_type_code' => 'corp', 'name' => 'Profit And Loss On Contracts'],
            ['old_id' => '9400', 'gl_type_code' => 'corp', 'name' => 'Recovered Costs'],
            ['old_id' => '9404', 'gl_type_code' => 'corp', 'name' => 'Recovered Benefits Cafe P&Ls'],
            ['old_id' => '9416', 'gl_type_code' => 'corp', 'name' => 'Recovered Busi Ins Cafe P&Ls'],
            ['old_id' => '9458', 'gl_type_code' => 'corp', 'name' => 'Recovered Admin Cafe P&Ls'],
            ['old_id' => '9495', 'gl_type_code' => 'corp', 'name' => 'Recovered Supr. Cafe P&Ls'],
            ['old_id' => '9499', 'gl_type_code' => 'corp', 'name' => 'Recovered P/R Tax Cafe P&Ls'],
            ['old_id' => '9504', 'gl_type_code' => 'corp', 'name' => 'Recovered Benefits Cafe'],
            ['old_id' => '9516', 'gl_type_code' => 'corp', 'name' => 'Recovered Busi Ins Cafe'],
            ['old_id' => '9558', 'gl_type_code' => 'corp', 'name' => 'Recovered Admin Fee Cafe'],
            ['old_id' => '9559', 'gl_type_code' => 'corp', 'name' => 'Recovered Mgt Fee Cafe'],
            ['old_id' => '9595', 'gl_type_code' => 'corp', 'name' => 'Recovered Supervision Cafe'],
            ['old_id' => '9599', 'gl_type_code' => 'corp', 'name' => 'Recovered P/R Taxes Cafe'],
            ['old_id' => '9604', 'gl_type_code' => 'corp', 'name' => 'Recovered Benefits Rest'],
            ['old_id' => '9616', 'gl_type_code' => 'corp', 'name' => 'Recovered Busi Ins. Rest'],
            ['old_id' => '9658', 'gl_type_code' => 'corp', 'name' => 'Recovered Admin Rest'],
            ['old_id' => '9695', 'gl_type_code' => 'corp', 'name' => 'Recovered Supervision Rest'],
            ['old_id' => '9699', 'gl_type_code' => 'corp', 'name' => 'Recovered P/R Taxes Rest'],
            ['old_id' => '9704', 'gl_type_code' => 'corp', 'name' => 'Recovered Benefits Vending'],
            ['old_id' => '9758', 'gl_type_code' => 'corp', 'name' => 'Recovered Admin Vending'],
            ['old_id' => '9799', 'gl_type_code' => 'corp', 'name' => 'Recovered P/R Taxes Vend'],
            ['old_id' => '9804', 'gl_type_code' => 'corp', 'name' => 'Recovered Benefits Indirect'],
            ['old_id' => '9899', 'gl_type_code' => 'corp', 'name' => 'Recovered P/R Taxes Indirect'],
        ];

        Schema::table('gl_accounts', function (Blueprint $table) {
            $table->string('old_id')->nullable();
        });

        foreach ($glAccounts as $glAccount)
            GlAccount::create([
                'old_id'          => $glAccount['old_id'],
                'name'            => $glAccount['name'],
                'gl_type_code_id' => \App\Models\GlTypeCode::where('code', $glAccount['gl_type_code'])->first()->id,
            ]);
    }
}
