<?php

namespace Database\Seeders;

use App\Models\GlAccount;
use Illuminate\Database\Seeder;

class GlSubAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $glSubAccounts = [
            ['old_id' => '0', 'parent_id' => 1010, 'name' => 'Cash Savings'],
            ['old_id' => '0', 'parent_id' => 1020, 'name' => 'Cash Executive Payroll'],
            ['old_id' => '0', 'parent_id' => 1025, 'name' => 'Cash Main Payroll'],
            ['old_id' => '0', 'parent_id' => 1030, 'name' => 'Cash Main Account'],
            ['old_id' => '0', 'parent_id' => 1035, 'name' => 'Cash Main Account'],
            ['old_id' => '0', 'parent_id' => 1040, 'name' => 'Cash Depository Bank'],
            ['old_id' => '0', 'parent_id' => 1050, 'name' => 'Petty Cash'],
            ['old_id' => '1', 'parent_id' => 1050, 'name' => 'Petty Cash Bill Changers'],
            ['old_id' => '2', 'parent_id' => 1050, 'name' => 'Petty Cash Bill Changers Advan'],
            ['old_id' => '0', 'parent_id' => 1070, 'name' => 'Investments'],
            ['old_id' => '1', 'parent_id' => 1070, 'name' => 'Investments - Book To Market'],
            ['old_id' => '0', 'parent_id' => 1100, 'name' => 'Accounts Receivable'],
            ['old_id' => '1', 'parent_id' => 1100, 'name' => 'Accounts Rec (Past Sales Tax)'],
            ['old_id' => '0', 'parent_id' => 1110, 'name' => 'Reserve For Bad Debts'],
            ['old_id' => '0', 'parent_id' => 1120, 'name' => 'Dividend Receivable'],
            ['old_id' => '0', 'parent_id' => 1130, 'name' => 'Cobra Receivable'],
            ['old_id' => '0', 'parent_id' => 1140, 'name' => 'Deposits And Exchanges'],
            ['old_id' => '0', 'parent_id' => 1144, 'name' => 'Misc. Receivables'],
            ['old_id' => '1', 'parent_id' => 1144, 'name' => 'Wage Attach Move To Liab'],
            ['old_id' => '2', 'parent_id' => 1144, 'name' => '401k Rec Move To Liab'],
            ['old_id' => '3', 'parent_id' => 1144, 'name' => 'Vending Bond Move To Liab'],
            ['old_id' => '1', 'parent_id' => 1150, 'name' => 'Credit Cards Rec Amer Exp'],
            ['old_id' => '2', 'parent_id' => 1150, 'name' => 'Credit Cards Rec Visa/Master'],
            ['old_id' => '3', 'parent_id' => 1150, 'name' => 'Credit Cards Rec Discover'],
            ['old_id' => '9', 'parent_id' => 1150, 'name' => 'House Charges'],
            ['old_id' => '0', 'parent_id' => 1180, 'name' => 'Rec From Vend Mach - Unisys Va'],
            ['old_id' => '0', 'parent_id' => 1200, 'name' => 'Inventory'],
            ['old_id' => '0', 'parent_id' => 1300, 'name' => 'Prepaid Expenses/Insurance'],
            ['old_id' => '0', 'parent_id' => 1310, 'name' => 'Prepaid Wkmn\'s Comp Premium'],
            ['old_id' => '0', 'parent_id' => 1330, 'name' => 'Prepaid State Taxes'],
            ['old_id' => '0', 'parent_id' => 1370, 'name' => 'Prepaid Other Expenses'],
            ['old_id' => '0', 'parent_id' => 1505, 'name' => 'Administrative Automobiles'],
            ['old_id' => '2', 'parent_id' => 1505, 'name' => 'Res For Administrative Autos'],
            ['old_id' => '0', 'parent_id' => 1507, 'name' => 'Office Machinery & Equipment'],
            ['old_id' => '2', 'parent_id' => 1507, 'name' => 'Res For Office Machines/Equip'],
            ['old_id' => '0', 'parent_id' => 1509, 'name' => 'Computer Equipment'],
            ['old_id' => '2', 'parent_id' => 1509, 'name' => 'Res For Computer Equipment'],
            ['old_id' => '0', 'parent_id' => 1510, 'name' => 'Computer Software'],
            ['old_id' => '2', 'parent_id' => 1510, 'name' => 'Res For Computer Software'],
            ['old_id' => '0', 'parent_id' => 1511, 'name' => 'Brock Cafeteria Equipment'],
            ['old_id' => '2', 'parent_id' => 1511, 'name' => 'Reserve For Cafeteria Equip'],
            ['old_id' => '0', 'parent_id' => 1516, 'name' => 'Res For Cafeteria Vehicles'],
            ['old_id' => '0', 'parent_id' => 1531, 'name' => 'NCI Restaurant Equipment'],
            ['old_id' => '2', 'parent_id' => 1531, 'name' => 'Res For NCI Rest Equipment'],
            ['old_id' => '0', 'parent_id' => 1580, 'name' => 'Vending Factory Mach/Equip'],
            ['old_id' => '2', 'parent_id' => 1580, 'name' => 'Reserve For Factory Mach/Equip'],
            ['old_id' => '0', 'parent_id' => 1584, 'name' => 'Vending Machines'],
            ['old_id' => '2', 'parent_id' => 1584, 'name' => 'Res For Vending Machines'],
            ['old_id' => '0', 'parent_id' => 1585, 'name' => 'Vending Vehicles'],
            ['old_id' => '2', 'parent_id' => 1585, 'name' => 'Res For Vending Vehicles'],
            ['old_id' => '0', 'parent_id' => 2000, 'name' => 'Accounts Payable'],
            ['old_id' => '0', 'parent_id' => 2001, 'name' => 'A/P Accruals And Reversals'],
            ['old_id' => '0', 'parent_id' => 2010, 'name' => 'Accounts Payable - Other'],
            ['old_id' => '1', 'parent_id' => 2010, 'name' => 'Accounts Payable - Bevaco Open'],
            ['old_id' => '0', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 106'],
            ['old_id' => '113', 'parent_id' => 2015, 'name' => 'Accts Payable Citbank Commissy'],
            ['old_id' => '119', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 119'],
            ['old_id' => '155', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 155'],
            ['old_id' => '160', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 160'],
            ['old_id' => '196', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 196'],
            ['old_id' => '197', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 197'],
            ['old_id' => '376', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 376'],
            ['old_id' => '385', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 385'],
            ['old_id' => '904', 'parent_id' => 2015, 'name' => 'Accts Payable On Contracts 904'],
            ['old_id' => '0', 'parent_id' => 2020, 'name' => 'Payroll Payable'],
            ['old_id' => '0', 'parent_id' => 2025, 'name' => 'Accrued Payroll Incentives'],
            ['old_id' => '0', 'parent_id' => 2100, 'name' => 'Federal Income Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2110, 'name' => 'Fica Taxes Withheld'],
            ['old_id' => '0', 'parent_id' => 2120, 'name' => 'Pa Income Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2130, 'name' => 'NJ Income Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2135, 'name' => 'NY Income Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2140, 'name' => 'DE Income Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2145, 'name' => 'VA Income Taxes Withheld'],
            ['old_id' => '0', 'parent_id' => 2150, 'name' => 'MD Income Taxes Withheld'],
            ['old_id' => '0', 'parent_id' => 2155, 'name' => 'Washington DC W/H Tax'],
            ['old_id' => '0', 'parent_id' => 2160, 'name' => 'Phila Wage Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2165, 'name' => 'Whitpain Township Wages W/H'],
            ['old_id' => '0', 'parent_id' => 2170, 'name' => 'Chester Wage Tax Withheld'],
            ['old_id' => '0', 'parent_id' => 2175, 'name' => 'Wilmington Wage Taxes Withheld'],
            ['old_id' => '0', 'parent_id' => 2180, 'name' => 'Local Taxes Withheld'],
            ['old_id' => '0', 'parent_id' => 2181, 'name' => 'Central Tax-W.Brandywine W/H'],
            ['old_id' => '0', 'parent_id' => 2182, 'name' => 'Del. Valley Tax-W.Brandy W/H'],
            ['old_id' => '0', 'parent_id' => 2185, 'name' => 'East Fallowfield Twn 1%'],
            ['old_id' => '0', 'parent_id' => 2190, 'name' => 'Norristown/Norriton Local Tax'],
            ['old_id' => '0', 'parent_id' => 2195, 'name' => 'Occupational Privilege Tax'],
            ['old_id' => '0', 'parent_id' => 2199, 'name' => 'Berkheimer Taxes Withheld'],
            ['old_id' => '0', 'parent_id' => 2240, 'name' => '401k Payable'],
            ['old_id' => '0', 'parent_id' => 2260, 'name' => 'Vending Union Dues Withheld'],
            ['old_id' => '0', 'parent_id' => 2265, 'name' => 'Ford Union Dues Withheld'],
            ['old_id' => '0', 'parent_id' => 2270, 'name' => 'Wage Attachments Withheld'],
            ['old_id' => '0', 'parent_id' => 2275, 'name' => 'Payback On 401k Loans'],
            ['old_id' => '0', 'parent_id' => 2280, 'name' => 'Vending Bonds Holdings'],
            ['old_id' => '0', 'parent_id' => 2300, 'name' => 'Unemployment Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2310, 'name' => 'DE Unemployment Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2320, 'name' => 'NJ Unemployment Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2330, 'name' => 'MD Unemployment Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2340, 'name' => 'VA Unemployment Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2350, 'name' => 'FED Unemployment Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2360, 'name' => 'FICA Payable - Employers'],
            ['old_id' => '0', 'parent_id' => 2365, 'name' => 'Workmans Comp Payable'],
            ['old_id' => '0', 'parent_id' => 2410, 'name' => 'PA Sales Tax Payable'],
            ['old_id' => '1', 'parent_id' => 2410, 'name' => 'PA Sales Tax Payable (OLD)'],
            ['old_id' => '0', 'parent_id' => 2420, 'name' => 'NJ Sales Tax Payable'],
            ['old_id' => '0', 'parent_id' => 2430, 'name' => 'DE Gross Receipts Tax Payable'],
            ['old_id' => '0', 'parent_id' => 2440, 'name' => 'MD Sales Tax Payable'],
            ['old_id' => '0', 'parent_id' => 2450, 'name' => 'VA Sales Taxes Payable'],
            ['old_id' => '0', 'parent_id' => 2460, 'name' => 'DC Sales Tax Payable'],
            ['old_id' => '0', 'parent_id' => 2480, 'name' => 'Phila Gross Receipts Tax Pay'],
            ['old_id' => '0', 'parent_id' => 2500, 'name' => 'Vacation Payable'],
            ['old_id' => '0', 'parent_id' => 2700, 'name' => 'Interest Payable On Debentures'],
            ['old_id' => '0', 'parent_id' => 2710, 'name' => 'Interest Payable Notes'],
            ['old_id' => '0', 'parent_id' => 2800, 'name' => 'Notes Payable'],
            ['old_id' => '0', 'parent_id' => 2820, 'name' => 'Debenture Bonds Payable'],
            ['old_id' => '0', 'parent_id' => 2830, 'name' => 'Notes Due Stockholders CNB'],
            ['old_id' => '0', 'parent_id' => 2840, 'name' => 'Notes Due Individuals CJB'],
            ['old_id' => '0', 'parent_id' => 2850, 'name' => 'Notes Due Stockholders LBJr'],
            ['old_id' => '0', 'parent_id' => 3000, 'name' => 'Common Stock Class A'],
            ['old_id' => '0', 'parent_id' => 3300, 'name' => 'Additional Paid In Capital'],
            ['old_id' => '0', 'parent_id' => 3400, 'name' => 'Contra Investments Bk To Mkt'],
            ['old_id' => '0', 'parent_id' => 3500, 'name' => 'S Corp Retained Earnings'],
            ['old_id' => '0', 'parent_id' => 3510, 'name' => 'C Corp Retained Earnings'],
            ['old_id' => '0', 'parent_id' => 3520, 'name' => 'Distributions/Withdrawals'],
            ['old_id' => '0', 'parent_id' => 4200, 'name' => 'Sales - Cafeteria Manual'],
            ['old_id' => '0', 'parent_id' => 4210, 'name' => 'Sales - Cafeteria Catering'],
            ['old_id' => '0', 'parent_id' => 4215, 'name' => 'Sales - Exempt Catering'],
            ['old_id' => '0', 'parent_id' => 4220, 'name' => 'Sales - Cafeteria OCS'],
            ['old_id' => '0', 'parent_id' => 4230, 'name' => 'Sales - Resident Vending'],
            ['old_id' => '1', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Candy/Snack'],
            ['old_id' => '2', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Hot Food'],
            ['old_id' => '3', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Hot Drnk'],
            ['old_id' => '4', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Cold Food'],
            ['old_id' => '5', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Frozen Foods'],
            ['old_id' => '6', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Bottled Drink'],
            ['old_id' => '7', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Can Soda'],
            ['old_id' => '8', 'parent_id' => 4230, 'name' => 'Sales - Res Vend Juice'],
            ['old_id' => '0', 'parent_id' => 4240, 'name' => 'Sales - Restaurant Food'],
            ['old_id' => '10', 'parent_id' => 4240, 'name' => 'Sales - Restaurant Liquor'],
            ['old_id' => '0', 'parent_id' => 4250, 'name' => 'Employee Store Sales'],
            ['old_id' => '0', 'parent_id' => 4280, 'name' => 'Sales - Vending (Machine)'],
            ['old_id' => '0', 'parent_id' => 4290, 'name' => 'Sales - Vending OCS'],
            ['old_id' => '0', 'parent_id' => 4400, 'name' => 'Miscellaneous Inc From Outside'],
            ['old_id' => '0', 'parent_id' => 4500, 'name' => 'Service Fee Income'],
            ['old_id' => '1', 'parent_id' => 4500, 'name' => 'Vending Commission To Units'],
            ['old_id' => '0', 'parent_id' => 4610, 'name' => 'Misc Income Cafeterias'],
            ['old_id' => '0', 'parent_id' => 4650, 'name' => 'Misc Income Restaurant'],
            ['old_id' => '0', 'parent_id' => 4680, 'name' => 'Misc Income Vending'],
            ['old_id' => '0', 'parent_id' => 4700, 'name' => 'Transportation Income Catering'],
            ['old_id' => '0', 'parent_id' => 4800, 'name' => 'Cafeteria Income From Vending'],
            ['old_id' => '0', 'parent_id' => 4930, 'name' => 'Gain/Loss On Stock Investments'],
            ['old_id' => '0', 'parent_id' => 4940, 'name' => 'Interest Income - Other'],
            ['old_id' => '2', 'parent_id' => 4940, 'name' => 'Dividend Income'],
            ['old_id' => '0', 'parent_id' => 4950, 'name' => 'P/L On Sale Of Assets'],
            ['old_id' => '0', 'parent_id' => 4990, 'name' => 'Cash Discounts'],
            ['old_id' => '1', 'parent_id' => 4990, 'name' => 'A/P Cash Discounts'],
            ['old_id' => '2', 'parent_id' => 4990, 'name' => 'Cash Discounts Purchasing'],
            ['old_id' => '0', 'parent_id' => 5000, 'name' => 'Food Costs - Cafeteria'],
            ['old_id' => '10', 'parent_id' => 5000, 'name' => 'Liquor Costs - Restaurants'],
            ['old_id' => '0', 'parent_id' => 5030, 'name' => 'Food Costs Resident Vending'],
            ['old_id' => '1', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Candy'],
            ['old_id' => '2', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Hot Food'],
            ['old_id' => '3', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Hot Drnk'],
            ['old_id' => '4', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Cold Food'],
            ['old_id' => '5', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend  Frozen'],
            ['old_id' => '6', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Bottled'],
            ['old_id' => '7', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Can Soda'],
            ['old_id' => '8', 'parent_id' => 5030, 'name' => 'Food Cost - Res Vend Juice'],
            ['old_id' => '0', 'parent_id' => 5050, 'name' => 'Employee Store Product Costs'],
            ['old_id' => '0', 'parent_id' => 5080, 'name' => 'Food Costs Vending'],
            ['old_id' => '1', 'parent_id' => 5080, 'name' => 'Food Costs - Vending Candy/Gum'],
            ['old_id' => '2', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Cigs'],
            ['old_id' => '3', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Hot Drnk'],
            ['old_id' => '4', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Cold Cup'],
            ['old_id' => '5', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Pastry/Sn'],
            ['old_id' => '6', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Soups'],
            ['old_id' => '7', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Can Soda'],
            ['old_id' => '8', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Juice'],
            ['old_id' => '9', 'parent_id' => 5080, 'name' => 'Prod Costs - Vending Sandwich'],
            ['old_id' => '0', 'parent_id' => 5090, 'name' => 'Prod Costs - Vending OCS'],
            ['old_id' => '10', 'parent_id' => 5090, 'name' => 'Vending Bottled soda'],
            ['old_id' => '0', 'parent_id' => 5100, 'name' => 'Paper Costs - Cafeterias'],
            ['old_id' => '0', 'parent_id' => 5130, 'name' => 'Paper Costs - Vend Hot Cups/Ld'],
            ['old_id' => '3', 'parent_id' => 5130, 'name' => 'Paper Costs - Vend Hot Cups/Ld'],
            ['old_id' => '0', 'parent_id' => 5180, 'name' => 'Paper Costs Vending'],
            ['old_id' => '1', 'parent_id' => 5180, 'name' => 'Paper Costs - Vending Other'],
            ['old_id' => '3', 'parent_id' => 5180, 'name' => 'Paper Costs - Vend Hot Cups/Ld'],
            ['old_id' => '4', 'parent_id' => 5180, 'name' => 'Paper Costs - Vend Coldcups/Ld'],
            ['old_id' => '5', 'parent_id' => 5180, 'name' => 'Paper Costs - Vend Soup Bwl/Sp'],
            ['old_id' => '0', 'parent_id' => 5200, 'name' => 'Labor - Direct'],
            ['old_id' => '1', 'parent_id' => 5200, 'name' => 'Labor - Direct Routeman'],
            ['old_id' => '2', 'parent_id' => 5200, 'name' => 'Labor - Direct General'],
            ['old_id' => '3', 'parent_id' => 5200, 'name' => 'Labor - Vending Mgt.'],
            ['old_id' => '10', 'parent_id' => 5200, 'name' => 'Labor - Charge Tips Reimbursed'],
            ['old_id' => '900', 'parent_id' => 5200, 'name' => 'Direct Labor Accruals/Adj'],
            ['old_id' => '0', 'parent_id' => 5210, 'name' => 'Labor - Supervision'],
            ['old_id' => '0', 'parent_id' => 5280, 'name' => 'Labor - Vacation Accrual'],
            ['old_id' => '0', 'parent_id' => 5299, 'name' => 'Payroll Taxes'],
            ['old_id' => '1', 'parent_id' => 5300, 'name' => 'Laundry'],
            ['old_id' => '2', 'parent_id' => 5300, 'name' => 'Cleaning Supplies'],
            ['old_id' => '3', 'parent_id' => 5300, 'name' => 'Casual Labor'],
            ['old_id' => '4', 'parent_id' => 5300, 'name' => 'Employee Benefits'],
            ['old_id' => '5', 'parent_id' => 5300, 'name' => 'Parking'],
            ['old_id' => '6', 'parent_id' => 5300, 'name' => 'Telephone'],
            ['old_id' => '7', 'parent_id' => 5300, 'name' => 'Equipment Rental'],
            ['old_id' => '8', 'parent_id' => 5300, 'name' => 'Technology Fee'],
            ['old_id' => '10', 'parent_id' => 5300, 'name' => 'Personnel Expense'],
            ['old_id' => '11', 'parent_id' => 5300, 'name' => 'Armored Car Service/Bank Fees'],
            ['old_id' => '12', 'parent_id' => 5300, 'name' => 'Public Relations'],
            ['old_id' => '13', 'parent_id' => 5300, 'name' => 'Rents'],
            ['old_id' => '14', 'parent_id' => 5300, 'name' => 'Maintenance And Repairs'],
            ['old_id' => '15', 'parent_id' => 5300, 'name' => 'Promotion Expenses'],
            ['old_id' => '16', 'parent_id' => 5300, 'name' => 'Business Insurance'],
            ['old_id' => '17', 'parent_id' => 5300, 'name' => 'Depreciation Of Bldg Equip'],
            ['old_id' => '18', 'parent_id' => 5300, 'name' => 'Utilities'],
            ['old_id' => '19', 'parent_id' => 5300, 'name' => 'Amortization Exp-Prepaid Inves'],
            ['old_id' => '20', 'parent_id' => 5300, 'name' => 'Marketing and Promotions'],
            ['old_id' => '21', 'parent_id' => 5300, 'name' => 'Office Supplies/Expenses'],
            ['old_id' => '22', 'parent_id' => 5300, 'name' => 'Uniforms'],
            ['old_id' => '23', 'parent_id' => 5300, 'name' => 'Business Taxes/Licenses'],
            ['old_id' => '24', 'parent_id' => 5300, 'name' => 'Unit Supplies'],
            ['old_id' => '25', 'parent_id' => 5300, 'name' => 'Shipping And Handling'],
            ['old_id' => '26', 'parent_id' => 5300, 'name' => 'PPE Supplies'],
            ['old_id' => '31', 'parent_id' => 5300, 'name' => 'Credit Card Fees'],
            ['old_id' => '32', 'parent_id' => 5300, 'name' => 'Trash Removal'],
            ['old_id' => '33', 'parent_id' => 5300, 'name' => 'Gross Receipts Taxes'],
            ['old_id' => '34', 'parent_id' => 5300, 'name' => ' DO NOT USE Smallwares'],
            ['old_id' => '35', 'parent_id' => 5300, 'name' => 'OCS Special Services'],
            ['old_id' => '36', 'parent_id' => 5300, 'name' => 'CaterTrax'],
            ['old_id' => '39', 'parent_id' => 5300, 'name' => 'Company Discounts'],
            ['old_id' => '40', 'parent_id' => 5300, 'name' => 'Diners Edge/Premier Dining'],
            ['old_id' => '41', 'parent_id' => 5300, 'name' => 'Taste Of Brandywine'],
            ['old_id' => '42', 'parent_id' => 5300, 'name' => 'Outside Meal Program'],
            ['old_id' => '44', 'parent_id' => 5300, 'name' => 'Free Meal Promotions'],
            ['old_id' => '45', 'parent_id' => 5300, 'name' => 'Outside Training And Seminars'],
            ['old_id' => '48', 'parent_id' => 5300, 'name' => 'Real Estate Taxes'],
            ['old_id' => '50', 'parent_id' => 5300, 'name' => 'Auto Repairs'],
            ['old_id' => '52', 'parent_id' => 5300, 'name' => 'Auto Gas/Tolls Etc.'],
            ['old_id' => '54', 'parent_id' => 5300, 'name' => 'Auto License/Registration'],
            ['old_id' => '56', 'parent_id' => 5300, 'name' => 'Auto Insurance'],
            ['old_id' => '67', 'parent_id' => 5300, 'name' => 'Vending Auto Depreciation'],
            ['old_id' => '73', 'parent_id' => 5300, 'name' => 'Building Maintenance'],
            ['old_id' => '76', 'parent_id' => 5300, 'name' => 'Memberships & Subscriptions'],
            ['old_id' => '87', 'parent_id' => 5300, 'name' => 'Vending Machine Depreciation'],
            ['old_id' => '90', 'parent_id' => 5300, 'name' => 'Miscellaneous'],
            ['old_id' => '95', 'parent_id' => 5300, 'name' => 'Negative Sale Tax'],
            ['old_id' => '0', 'parent_id' => 5400, 'name' => 'Vending Commission Expenses'],
            ['old_id' => '0', 'parent_id' => 5700, 'name' => 'Unrecovered Contract Costs'],
            ['old_id' => '0', 'parent_id' => 5800, 'name' => 'Administration Allocation'],
            ['old_id' => '0', 'parent_id' => 5900, 'name' => 'Management Fee Allocation'],
            ['old_id' => '0', 'parent_id' => 6100, 'name' => 'Executive Salaries'],
            ['old_id' => '10', 'parent_id' => 6100, 'name' => 'Admin/Acct Salaries'],
            ['old_id' => '15', 'parent_id' => 6100, 'name' => 'Operations Salaries'],
            ['old_id' => '20', 'parent_id' => 6100, 'name' => 'Sales Salaries'],
            ['old_id' => '25', 'parent_id' => 6100, 'name' => 'Payroll Taxes On Indirect'],
            ['old_id' => '30', 'parent_id' => 6100, 'name' => 'Emp Benefits On Indirect'],
            ['old_id' => '35', 'parent_id' => 6100, 'name' => 'Advertising For Personnel'],
            ['old_id' => '40', 'parent_id' => 6100, 'name' => 'Casual Labor'],
            ['old_id' => '0', 'parent_id' => 6200, 'name' => 'Office Rents'],
            ['old_id' => '10', 'parent_id' => 6200, 'name' => 'Telephone/Fax Expenses'],
            ['old_id' => '12', 'parent_id' => 6200, 'name' => 'Cellular Phone Expense'],
            ['old_id' => '15', 'parent_id' => 6200, 'name' => 'Other Utilities'],
            ['old_id' => '20', 'parent_id' => 6200, 'name' => 'Equipment Rentals'],
            ['old_id' => '25', 'parent_id' => 6200, 'name' => 'Building Maintenance'],
            ['old_id' => '0', 'parent_id' => 6300, 'name' => 'Office Forms'],
            ['old_id' => '6', 'parent_id' => 6300, 'name' => 'Copy Machine Expenses W/Paper'],
            ['old_id' => '10', 'parent_id' => 6300, 'name' => 'Computer Maint/Supp(Not Forms)'],
            ['old_id' => '12', 'parent_id' => 6300, 'name' => 'Binding Machine Exp Not Depr'],
            ['old_id' => '15', 'parent_id' => 6300, 'name' => 'Office Supplies'],
            ['old_id' => '17', 'parent_id' => 6300, 'name' => 'Other Office Expenses'],
            ['old_id' => '18', 'parent_id' => 6300, 'name' => 'Postage and Related Expenses'],
            ['old_id' => '19', 'parent_id' => 6300, 'name' => 'Bank Charges'],
            ['old_id' => '20', 'parent_id' => 6300, 'name' => 'Forms/Supplies For Units'],
            ['old_id' => '22', 'parent_id' => 6300, 'name' => 'Cafeteria Wear'],
            ['old_id' => '25', 'parent_id' => 6300, 'name' => 'Office Equipment Depreciation'],
            ['old_id' => '26', 'parent_id' => 6300, 'name' => 'Computer Equip Depreciation'],
            ['old_id' => '27', 'parent_id' => 6300, 'name' => 'Computer Software Depreciation'],
            ['old_id' => '30', 'parent_id' => 6300, 'name' => 'Business Insurance Expenses'],
            ['old_id' => '0', 'parent_id' => 6400, 'name' => 'Operations Expenses'],
            ['old_id' => '25', 'parent_id' => 6400, 'name' => 'Payroll Taxes On Operations'],
            ['old_id' => '0', 'parent_id' => 6500, 'name' => 'Sales Expenses'],
            ['old_id' => '0', 'parent_id' => 6600, 'name' => 'Exec Auto Repairs'],
            ['old_id' => '10', 'parent_id' => 6600, 'name' => 'Exec Auto Gas Expenses'],
            ['old_id' => '15', 'parent_id' => 6600, 'name' => 'Exec Auto Insurance/Regist'],
            ['old_id' => '20', 'parent_id' => 6600, 'name' => 'Exec Auto Depreciation'],
            ['old_id' => '25', 'parent_id' => 6600, 'name' => 'Exec Auto Rental'],
            ['old_id' => '0', 'parent_id' => 6700, 'name' => 'Corp. Public Relations'],
            ['old_id' => '10', 'parent_id' => 6700, 'name' => 'Corp. Advertising'],
            ['old_id' => '15', 'parent_id' => 6700, 'name' => 'Memberships and Subscriptions'],
            ['old_id' => '16', 'parent_id' => 6700, 'name' => 'Seminars DMs'],
            ['old_id' => '17', 'parent_id' => 6700, 'name' => 'Employee Relations'],
            ['old_id' => '20', 'parent_id' => 6700, 'name' => 'Contributions'],
            ['old_id' => '25', 'parent_id' => 6700, 'name' => 'Entertainment'],
            ['old_id' => '30', 'parent_id' => 6700, 'name' => 'Local Taxes'],
            ['old_id' => '35', 'parent_id' => 6700, 'name' => 'Legal And Accounting'],
            ['old_id' => '40', 'parent_id' => 6700, 'name' => 'Pension Expense'],
            ['old_id' => '45', 'parent_id' => 6700, 'name' => 'Executive Misc Expenses'],
            ['old_id' => '0', 'parent_id' => 7100, 'name' => 'FICA Expense'],
            ['old_id' => '10', 'parent_id' => 7100, 'name' => 'Unemployment Ins Expense'],
            ['old_id' => '15', 'parent_id' => 7100, 'name' => 'Workmans Comp Expense'],
            ['old_id' => '20', 'parent_id' => 7100, 'name' => 'Health Dental Premiums'],
            ['old_id' => '25', 'parent_id' => 7100, 'name' => 'Health Dental Recovered'],
            ['old_id' => '30', 'parent_id' => 7100, 'name' => 'Disability Insurance'],
            ['old_id' => '35', 'parent_id' => 7100, 'name' => 'Disability Premiums Recovered'],
            ['old_id' => '40', 'parent_id' => 7100, 'name' => '401k Employer Contribution'],
            ['old_id' => '0', 'parent_id' => 7500, 'name' => 'Interest Expense'],
            ['old_id' => '6', 'parent_id' => 7500, 'name' => 'Inputed Interest @ T-Bill Rate'],
            ['old_id' => '10', 'parent_id' => 7500, 'name' => 'Provision For Bad Debts'],
            ['old_id' => '15', 'parent_id' => 7500, 'name' => 'Prior Year Adjustments'],
            ['old_id' => '25', 'parent_id' => 7500, 'name' => 'Unabsorbed Unit Costs'],
            ['old_id' => '0', 'parent_id' => 7600, 'name' => 'Extraordinary Expenses'],
            ['old_id' => '0', 'parent_id' => 7700, 'name' => 'Net Corp Income Taxes'],
            ['old_id' => '0', 'parent_id' => 9300, 'name' => 'Profit And Loss On Contracts'],
            ['old_id' => '0', 'parent_id' => 9400, 'name' => 'Recovered Costs'],
            ['old_id' => '0', 'parent_id' => 9404, 'name' => 'Recovered Benefits Cafe P&Ls'],
            ['old_id' => '0', 'parent_id' => 9416, 'name' => 'Recovered Busi Ins Cafe P&Ls'],
            ['old_id' => '0', 'parent_id' => 9458, 'name' => 'Recovered Admin Cafe P&Ls'],
            ['old_id' => '0', 'parent_id' => 9495, 'name' => 'Recovered Supr. Cafe P&Ls'],
            ['old_id' => '0', 'parent_id' => 9499, 'name' => 'Recovered P/R Tax Cafe P&Ls'],
            ['old_id' => '0', 'parent_id' => 9504, 'name' => 'Recovered Benefits Cafe'],
            ['old_id' => '0', 'parent_id' => 9516, 'name' => 'Recovered Busi Ins Cafe'],
            ['old_id' => '0', 'parent_id' => 9558, 'name' => 'Recovered Admin Fee Cafe'],
            ['old_id' => '0', 'parent_id' => 9559, 'name' => 'Recovered Mgt Fee Cafe'],
            ['old_id' => '0', 'parent_id' => 9595, 'name' => 'Recovered Supervision Cafe'],
            ['old_id' => '0', 'parent_id' => 9599, 'name' => 'Recovered P/R Taxes Cafe'],
            ['old_id' => '0', 'parent_id' => 9604, 'name' => 'Recovered Benefits Rest'],
            ['old_id' => '0', 'parent_id' => 9616, 'name' => 'Recovered Busi Ins. Rest'],
            ['old_id' => '0', 'parent_id' => 9658, 'name' => 'Recovered Admin Rest'],
            ['old_id' => '0', 'parent_id' => 9695, 'name' => 'Recovered Supervision Rest'],
            ['old_id' => '0', 'parent_id' => 9699, 'name' => 'Recovered P/R Taxes Rest'],
            ['old_id' => '0', 'parent_id' => 9704, 'name' => 'Recovered Benefits Vending'],
            ['old_id' => '0', 'parent_id' => 9758, 'name' => 'Recovered Admin Vending'],
            ['old_id' => '0', 'parent_id' => 9799, 'name' => 'Recovered P/R Taxes Vend'],
            ['old_id' => '0', 'parent_id' => 9804, 'name' => 'Recovered Benefits Indirect'],
            ['old_id' => '0', 'parent_id' => 9899, 'name' => 'Recovered P/R Taxes Indirect'],
        ];

        foreach ($glSubAccounts as $glSubAccount)
            GlAccount::create([
                'old_id'    => $glSubAccount['old_id'],
                'name'      => $glSubAccount['name'],
                'parent_id' => \App\Models\GlAccount::where('old_id', $glSubAccount['parent_id'])->first()->id,
            ]);
    }
}
