export const CATERING_ORDER = {
  id: '',
  description: '',
  items: [],
  deliveryDate: '',
  headCount: '',
  phoneNumber: '',
  orderBy: '',
  orderFor: '',
  orderDate: '',
  isTaxable: false,
  tax: '',
  shipToName: '',
  shipToAddress: '',
  billToName: '',
  billToAddress: '',
  isCashOrder: false,
  chargeNumber: '',
}
