export const WeeklyReportsTypes = [
  {
    id: 0,
    name: 'Weekly Operating',
    type: 'OPERATING',
    typePeriod: 'WEEKLY',
  },
  {
    id: 1,
    name: 'Weekly Complete',
    type: 'COMPLETE',
    typePeriod: 'WEEKLY',
  },
  {
    id: 2,
    name: 'Weekly Catering',
    type: 'CATERING',
    typePeriod: 'WEEKLY',
  },
  {
    id: 3,
    name: 'Weekly Inventory',
    type: 'INVENTORY',
    typePeriod: 'WEEKLY',
  },
  {
    id: 4,
    name: 'Weekly Expense',
    type: 'EXPENSE',
    typePeriod: 'WEEKLY',
  },
  {
    id: 5,
    name: 'Weekly Labor',
    type: 'LABOR',
    typePeriod: 'WEEKLY',
  },
  {
    id: 6,
    name: 'Purchase Details',
    type: 'PURCHASE',
  },
  {
    id: 7,
    name: 'Register Closeouts',
    type: 'CLOSEOUT',
  },
]

export const MonthlyReportsTypes = [
  {
    id: 0,
    value: 'monthlyOperating',
    name: 'Monthly Operating',
    type: 'OPERATING',
    typePeriod: 'MONTHLY',
  },
  {
    id: 1,
    value: 'monthlyComplete',
    name: 'Monthly Complete',
    type: 'COMPLETE',
    typePeriod: 'MONTHLY',
  },
  {
    id: 2,
    value: 'monthlyCatering',
    name: 'Monthly Catering',
    type: 'CATERING',
    typePeriod: 'MONTHLY',
  },
  {
    id: 3,
    value: 'monthlyInventory',
    name: 'Monthly Inventory',
    type: 'INVENTORY',
    typePeriod: 'MONTHLY',
  },
  {
    id: 4,
    value: 'monthlyExpense',
    name: 'Monthly Expense',
    type: 'EXPENSE',
    typePeriod: 'MONTHLY',
  },
  {
    id: 5,
    value: 'monthlyLabor',
    name: 'Monthly Labor',
    type: 'LABOR',
    typePeriod: 'MONTHLY',
  },
  {
    id: 6,
    value: 'purchaseDetails',
    name: 'Purchase Details',
    type: 'PURCHASE',
  },
  {
    id: 7,
    value: 'registerCloseouts',
    name: 'Register Closeouts',
    type: 'CLOSEOUT',
  },
]

export const locationReportTypes = [
  {
    id: 0,
    value: 'weeklyOperating',
    name: 'Weekly Operating',
    type: 'OPERATING',
    typePeriod: 'WEEKLY',
  },
  {
    id: 1,
    value: 'weeklyComplete',
    type: 'COMPLETE',
    name: 'Weekly Complete',
    typePeriod: 'WEEKLY',
  },
  {
    id: 2,
    value: 'monthlyOperating',
    name: 'Monthly Operating',
    typePeriod: 'MONTHLY',
    type: 'OPERATING',
  },
  {
    id: 3,
    value: 'monthlyComplete',
    name: 'Monthly Complete',
    type: 'COMPLETE',
    typePeriod: 'MONTHLY',
  },
  {
    id: 4,
    value: 'weeklyCatering',
    name: 'Weekly Catering',
    type: 'CATERING',
    typePeriod: 'WEEKLY',
  },
  {
    id: 5,
    value: 'weeklyCateringStatistics',
    name: 'Weekly Catering Statistics',
    type: 'CATERING_STATISTICS',
    typePeriod: 'WEEKLY',
  },
  {
    id: 6,
    value: 'purchaseOrders',
    name: 'Purchase Orders',
    type: 'PURCHASE',
  },
  {
    id: 7,
    value: 'weeklyPurchases',
    name: 'Weekly Purchases',
    typePeriod: 'WEEKLY',
    type: 'PURCHASE',
  },
  {
    id: 8,
    value: 'laborSchedule',
    name: 'Labor Schedule',
    type: 'LABOR',
  },
  {
    id: 9,
    value: 'weeklyInventoryDetails',
    name: 'Weekly Inventory Details',
    typePeriod: 'WEEKLY',
    type: 'INVENTORY',
  },
  {
    id: 10,
    value: 'weeklyExpenseDetails',
    name: 'Weekly Expense Details',
    typePeriod: 'WEEKLY',
    type: 'EXPENSE',
  },
  {
    id: 11,
    value: 'registerCloseDetails',
    name: 'Register Close Details',
    type: 'CLOSEOUT',
  },
]
