export const UNIT = {
  code: '',
  address: '',
  name: '',
  city: {
    id: '',
    name: '',
    tax: '',
    createdAt: '',
    updatedAt: '',
    state: {
      id: '',
      code: '',
    },
  },
  district: '',
  county: '',
  startPeriod: '',
  population: '',
  state: {
    id: '',
    code: '',
    salesTaxCafeteria: '',
    salesTaxVending: '',
    salesTaxRestaurant: '',
    salesTaxStore: '',
    grossReceiptsTax: '',
    createdAt: '',
    updatedAt: '',
    cities: [],
    counties: [],
  },
  managerFirstName: '',
  zip: '',
  managerLastName: '',
  payrollPassword: '',
  emailAccount: '',
  users: [],
  sysco: '',
  payrollTaxPercent: '',
  benefitsAmount: '',
  vendingIncome: '',
  commissionAmount: '',
  vacationAmount: '',
  isVending: false,
  isActive: false,
  businessInsuranceAmount: '',
  managementFeeType: '',
  managementAmount: '',
  managementPercent: '',
  administrativeFeeType: '',
  administrativeAmount: '',

  administrativePercent: '',
  supportAmount: '',
  supportFeeType: '',
  supportPercent: '',
  benefitsPercent: '',
  regTax: '',
  commissionPercent: '',
  isKronos: false,
}
